config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # #get 'pages/index'

  root 'pages#index'

  resources :bank_accounts, only: %i[show index]

  namespace :api do
    namespace :v1 do
      post 'bank_accounts/new_transaction', to: 'bank_accounts#new_transaction'
    end
  end
end

app/models/account_transaction.rb
# frozen_string_literal: true

class AccountTransaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION_TYPES = %w[withdraw deposit].freeze

  validates :bank_account, presence: true
  validates :amount, numericality: true, presence: true
  validates :transaction_type, inclusion: { in: TRANSACTION_TYPES }, presence: true
  validates :transaction_number, uniqueness: true, presence: true

  before_validation :load_defaults

  def load_defaults
    self.transaction_number = SecureRandom.uuid if new_record?
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
# frozen_string_literal: true

class BankAccount < ApplicationRecord
  belongs_to :client

  validates :client, presence: true
  validates :account_number, presence: true, uniqueness: true
  validates :balance, numericality: true, presence: true

  before_validation :load_defaults

  has_many :account_transactions

  def load_defaults
    self.balance = 0.00 if new_record?
  end

  def to_s
    account_number
  end
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :client_number, presence: true, uniqueness: true

  has_many :bank_accounts

  before_save :format_name

  def format_name
    self.first_name = first_name.upcase
    self.last_name = last_name.upcase
    self.middle_name = middle_name.upcase
  end

  def to_s
    "#{last_name}, #{first_name}, #{middle_name}"
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
    module V1 
        class BankAccountsController < ApplicationController
            def new_transaction
                amount = params[:amount]
                transaction_type = params[:transaction_type]
                bank_account_id = params[:bank_account_id]

                errors = ::BankAccounts::ValidateNewTransaction.new(
                    amount: amount,
                    transaction_type: transaction_type,
                    bank_account_id: bank_account_id
                ).execute!

                if errors.size > 0
                    render json: { errors: errors }, status: 402
                else
                    bank_account = ::BankAccounts::PerformTransaction.new(
                        amount: amount,
                        transaction_type: transaction_type,
                        bank_account_id: bank_account_id
                    ).execute!
                    render json: {balance: bank_account.balance}
                end
                
            end
        end
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bank_accounts_controller.rb
# frozen_string_literal: true

class BankAccountsController < ApplicationController
  def index
    @bank_accounts = BankAccount.all
  end

  def show
    @bank_account = BankAccount.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def number_of_accounts
    BankAccount.count
  end

  def number_of_clients
    Client.count
  end
end

app/views/bank_accounts/index.html.haml
%h1
    Bank Accounts

%table.table.table-bordered
    %thead
        %tr
            %th Account Number
            %th Balance
            %th Actions
    %tbody
        - @bank_accounts.each do | bank_account | 
            %tr
                %td #{bank_account.account_number}
                %td #{number_to_currency(bank_account.balance, unit: "GBP ")}
                %td 
                    = link_to bank_account, class: "btn btn-primary" do
                        Show

app/views/bank_accounts/show.html.haml
%h1
    Account Number: #{@bank_account.account_number}
    %small
        #{@bank_account.client}

= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do
    New Transaction

%table.table.table-bordered
    %thead
        %tr
            %th Date of Transaction
            %th Transaction Type
            %th Amount
        %tbody
            - @bank_account.account_transactions.each do | transaction |
                %tr
                    %td #{transaction.created_at}
                    %td #{transaction.transaction_type}
                    %td #{number_to_currency(transaction.amount, unit: "GBP ")}
        %tr
            %th
            %th Balance
            %th #{number_to_currency(@bank_account.balance, unit: "GBP ")}

#parameters{ data: { bank_account_id: @bank_account.id } }

#modal-transaction.modal.hide.fade.modal-fade 
    .modal-dialog
        .modal-content
            .modal-header
                %button.close{type: 'button', data:{dismiss:'modal'}}
                    %span{aria:{hidden:'true'}}
                        %i.fa.fa-close
                    %span.sr-only Close
                    %h4.modal-title
                        New Transaction
            .modal-body 
                .row
                    .col-md-12
                        .notification
                .row
                    .col-md-6
                        %label
                            Amount
                        = text_field_tag :amount, 0.00, id: 'input-amount', class: "form-control"
                    .col-md-6
                        %label
                            Transaction Type
                        = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: 'form-control'
            .modal-footer
                %button#btn-close.btn-default{type:'button', date:{dismiss:'modal'}} Close
                %button#btn-save.btn-default{type:'button'} Save
                                                

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankHaml</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>   
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.haml
%h1 
    My Bank

.row
    .col-md-12
        %h2
            Number of Accounts #{number_of_accounts}
        %h2
            Number of Clients #{number_of_clients} 
.row
    .col-md-12
        = link_to bank_accounts_path do
            Bank Accounts